// ClipboardManager.swift
// --------------------
// Quản lý lịch sử clipboard:
//   - Theo dõi sự thay đổi của NSPasteboard.general bằng Timer.
//   - Bỏ qua dữ liệu nhạy cảm từ các trình quản lý mật khẩu (1Password, Bitwarden, v.v.).
//   - Bỏ qua các kiểu pasteboard nhạy cảm (transient, concealed).
//   - Giới hạn số mục tối đa.
//   - Ghi/đọc lịch sử ra file JSON dùng chung chứa text, appName và timestamp.

import AppKit
import Foundation

struct ClipboardEntry: Identifiable, Codable, Equatable {
    let id: UUID
    let text: String
    let appName: String
    let timestamp: Date
    /// Đường dẫn file ảnh PNG trên đĩa (nil nếu mục này là text).
    /// Ảnh lưu ra file thay vì nhồi raw bytes vào JSON để tránh phình lịch sử.
    var imagePath: String?

    var isImage: Bool { imagePath != nil }

    // Decode tương thích ngược: file lịch sử cũ không có khoá imagePath.
    enum CodingKeys: String, CodingKey {
        case id, text, appName, timestamp, imagePath
    }

    init(id: UUID, text: String, appName: String, timestamp: Date, imagePath: String? = nil) {
        self.id = id
        self.text = text
        self.appName = appName
        self.timestamp = timestamp
        self.imagePath = imagePath
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(UUID.self, forKey: .id)
        text = try c.decode(String.self, forKey: .text)
        appName = try c.decode(String.self, forKey: .appName)
        timestamp = try c.decode(Date.self, forKey: .timestamp)
        imagePath = try c.decodeIfPresent(String.self, forKey: .imagePath)
    }
}

@MainActor
final class ClipboardManager {
    static let shared = ClipboardManager()

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private(set) var history: [ClipboardEntry] = []

    var limit = 40
    var enabled = true

    private var bowGoDir: URL {
        let appSupport = FileManager.default.urls(
            for: .applicationSupportDirectory, in: .userDomainMask
        ).first!
        return appSupport.appendingPathComponent("BowGo", isDirectory: true)
    }

    private var historyFileURL: URL {
        bowGoDir.appendingPathComponent("clipboard_history.json")
    }

    /// Thư mục chứa ảnh đã copy (mỗi ảnh một file PNG theo UUID của entry).
    private var imagesDir: URL {
        bowGoDir.appendingPathComponent("clipboard_images", isDirectory: true)
    }

    private init() {
        loadHistory()
    }

    func start() {
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.checkClipboard()
            }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func checkClipboard() {
        guard enabled else { return }
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        // 1. Kiểm tra ứng dụng nhạy cảm (password managers) đang active
        var appName = "System"
        if let frontApp = NSWorkspace.shared.frontmostApplication {
            appName = frontApp.localizedName ?? "Unknown"
            let bundleId = frontApp.bundleIdentifier ?? ""
            let sensitiveBundles = [
                "com.agilebits.onepassword",
                "com.bitwarden.desktop",
                "com.dashlane.dashlane",
                "com.elpass.elpass",
                "com.keepersecurity.Keeper",
                "org.keepassxc.keepassxc",
                "com.apple.keychainaccess"
            ]
            if sensitiveBundles.contains(where: { bundleId.lowercased().contains($0) }) {
                return
            }
        }

        // 2. Kiểm tra các kiểu dữ liệu transient/concealed của pasteboard
        let types = pasteboard.types ?? []
        let ignoredTypes = [
            "org.nspasteboard.TransientType",
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword",
            "de.petermaurer.TransientPasteboardType"
        ]
        let containsSensitiveType = types.map { $0.rawValue }.contains { type in
            ignoredTypes.contains { ignored in type.contains(ignored) }
        }
        if containsSensitiveType {
            return
        }

        // 3. Đọc dữ liệu text (ưu tiên — copy text đôi khi kèm cả ảnh RTF)
        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            // Bỏ qua các đoạn text quá lớn (> 10,000 ký tự) để tránh tốn RAM
            guard text.count < 10000 else { return }
            addEntry(text, appName: appName)
            return
        }

        // 4. Không có text -> thử đọc ẢNH (chụp màn hình / copy ảnh).
        if let imageData = readImageData(from: pasteboard) {
            addImageEntry(imageData, appName: appName)
        }
    }

    /// Lấy dữ liệu ảnh PNG từ pasteboard. Trả về data PNG đã chuẩn hoá, hoặc nil.
    private func readImageData(from pasteboard: NSPasteboard) -> Data? {
        // Ưu tiên PNG, sau đó TIFF (định dạng chụp màn hình macOS hay dùng).
        let pngType = NSPasteboard.PasteboardType.png
        let tiffType = NSPasteboard.PasteboardType.tiff

        if let png = pasteboard.data(forType: pngType) {
            return png
        }
        if let tiff = pasteboard.data(forType: tiffType),
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            return png
        }
        return nil
    }

    private func addEntry(_ text: String, appName: String) {
        // Nếu đã tồn tại trong lịch sử, xoá phần tử cũ để đẩy bản mới lên đầu
        if let index = history.firstIndex(where: { !$0.isImage && $0.text == text }) {
            history.remove(at: index)
        }

        let newEntry = ClipboardEntry(id: UUID(), text: text, appName: appName, timestamp: Date())
        history.insert(newEntry, at: 0)
        enforceLimit()
        saveHistory()
    }

    /// Lưu ảnh ra file PNG rồi thêm một mục ảnh vào đầu lịch sử.
    private func addImageEntry(_ pngData: Data, appName: String) {
        let id = UUID()
        let dir = imagesDir
        if !FileManager.default.fileExists(atPath: dir.path) {
            try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        }
        let fileURL = dir.appendingPathComponent("\(id.uuidString).png")
        guard (try? pngData.write(to: fileURL, options: .atomic)) != nil else { return }

        // text dùng làm nhãn hiển thị/tìm kiếm cho mục ảnh.
        let entry = ClipboardEntry(
            id: id, text: "[Hình ảnh]", appName: appName,
            timestamp: Date(), imagePath: fileURL.path
        )
        history.insert(entry, at: 0)
        enforceLimit()
        saveHistory()
    }

    /// Cắt lịch sử về `limit`, xoá kèm file ảnh của các mục bị loại.
    private func enforceLimit() {
        guard history.count > limit else { return }
        let dropped = history[limit...]
        for entry in dropped { deleteImageFile(for: entry) }
        history = Array(history.prefix(limit))
    }

    /// Xoá file ảnh trên đĩa của một entry (nếu có).
    private func deleteImageFile(for entry: ClipboardEntry) {
        guard let path = entry.imagePath else { return }
        try? FileManager.default.removeItem(atPath: path)
    }

    func clearHistory() {
        for entry in history { deleteImageFile(for: entry) }
        history.removeAll()
        saveHistory()
    }

    /// Xoá một mục lẻ khỏi lịch sử (dùng cho phím Delete trong cửa sổ lịch sử).
    func removeEntry(id: UUID) {
        if let entry = history.first(where: { $0.id == id }) {
            deleteImageFile(for: entry)
        }
        history.removeAll { $0.id == id }
        saveHistory()
    }

    private func loadHistory() {
        guard let data = try? Data(contentsOf: historyFileURL) else { return }
        if let loaded = try? JSONDecoder().decode([ClipboardEntry].self, from: data) {
            self.history = loaded
        } else {
            // Nếu decode kiểu mới lỗi (do định dạng cũ là [String]), reset
            self.history = []
        }
    }

    private func saveHistory() {
        let url = historyFileURL
        let dir = url.deletingLastPathComponent()
        if !FileManager.default.fileExists(atPath: dir.path) {
            try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        }
        guard let data = try? JSONEncoder().encode(history) else { return }
        try? data.write(to: url, options: .atomic)
    }
}
