// LegacyCodeTable.swift
// ---------------------
// Bảng mã CŨ: chuyển Unicode <-> TCVN3 (ABC, font .VnTime) và VNI-Windows
// (font VNI-Times). Dữ liệu trích từ bảng mã của PHTV/OpenKey
// (EngineCodeTableLookup) — đã kiểm chứng, không gõ tay.
//
// TCVN3: mỗi ký tự có dấu là 1 byte (0xA1..0xFE) trong vùng Latin-1.
// VNI-Windows: ký tự có dấu thường là 2 ký tự (chữ gốc + ký tự dấu rời), vd
//   "á" = "a" + "ù"(0xF9). Vài ký tự là 1 (đ -> "ñ").
//
// Bảng dưới sinh tự động; xem scripts/gen ở lịch sử commit nếu cần dựng lại.

enum LegacyCodeTable {

    // unicodeToTCVN: 134 ký tự
    static let unicodeToTCVN: [Character: String] = [
        "\u{C0}": "\u{B5}",
        "\u{C1}": "\u{B8}",
        "\u{C2}": "\u{A2}",
        "\u{C3}": "\u{B7}",
        "\u{C8}": "\u{CC}",
        "\u{C9}": "\u{D0}",
        "\u{CA}": "\u{A3}",
        "\u{CC}": "\u{D7}",
        "\u{CD}": "\u{DD}",
        "\u{D2}": "\u{DF}",
        "\u{D3}": "\u{E3}",
        "\u{D4}": "\u{A4}",
        "\u{D5}": "\u{E2}",
        "\u{D9}": "\u{EF}",
        "\u{DA}": "\u{F3}",
        "\u{DD}": "\u{FD}",
        "\u{E0}": "\u{B5}",
        "\u{E1}": "\u{B8}",
        "\u{E2}": "\u{A9}",
        "\u{E3}": "\u{B7}",
        "\u{E8}": "\u{CC}",
        "\u{E9}": "\u{D0}",
        "\u{EA}": "\u{AA}",
        "\u{EC}": "\u{D7}",
        "\u{ED}": "\u{DD}",
        "\u{F2}": "\u{DF}",
        "\u{F3}": "\u{E3}",
        "\u{F4}": "\u{AB}",
        "\u{F5}": "\u{E2}",
        "\u{F9}": "\u{EF}",
        "\u{FA}": "\u{F3}",
        "\u{FD}": "\u{FD}",
        "\u{102}": "\u{A1}",
        "\u{103}": "\u{A8}",
        "\u{110}": "\u{A7}",
        "\u{111}": "\u{AE}",
        "\u{128}": "\u{DC}",
        "\u{129}": "\u{DC}",
        "\u{168}": "\u{F2}",
        "\u{169}": "\u{F2}",
        "\u{1A0}": "\u{A5}",
        "\u{1A1}": "\u{AC}",
        "\u{1AF}": "\u{A6}",
        "\u{1B0}": "\u{AD}",
        "\u{1EA0}": "\u{B9}",
        "\u{1EA1}": "\u{B9}",
        "\u{1EA2}": "\u{B6}",
        "\u{1EA3}": "\u{B6}",
        "\u{1EA4}": "\u{CA}",
        "\u{1EA5}": "\u{CA}",
        "\u{1EA6}": "\u{C7}",
        "\u{1EA7}": "\u{C7}",
        "\u{1EA8}": "\u{C8}",
        "\u{1EA9}": "\u{C8}",
        "\u{1EAA}": "\u{C9}",
        "\u{1EAB}": "\u{C9}",
        "\u{1EAC}": "\u{CB}",
        "\u{1EAD}": "\u{CB}",
        "\u{1EAE}": "\u{BE}",
        "\u{1EAF}": "\u{BE}",
        "\u{1EB0}": "\u{BB}",
        "\u{1EB1}": "\u{BB}",
        "\u{1EB2}": "\u{BC}",
        "\u{1EB3}": "\u{BC}",
        "\u{1EB4}": "\u{BD}",
        "\u{1EB5}": "\u{BD}",
        "\u{1EB6}": "\u{C6}",
        "\u{1EB7}": "\u{C6}",
        "\u{1EB8}": "\u{D1}",
        "\u{1EB9}": "\u{D1}",
        "\u{1EBA}": "\u{CE}",
        "\u{1EBB}": "\u{CE}",
        "\u{1EBC}": "\u{CF}",
        "\u{1EBD}": "\u{CF}",
        "\u{1EBE}": "\u{D5}",
        "\u{1EBF}": "\u{D5}",
        "\u{1EC0}": "\u{D2}",
        "\u{1EC1}": "\u{D2}",
        "\u{1EC2}": "\u{D3}",
        "\u{1EC3}": "\u{D3}",
        "\u{1EC4}": "\u{D4}",
        "\u{1EC5}": "\u{D4}",
        "\u{1EC6}": "\u{D6}",
        "\u{1EC7}": "\u{D6}",
        "\u{1EC8}": "\u{D8}",
        "\u{1EC9}": "\u{D8}",
        "\u{1ECA}": "\u{DE}",
        "\u{1ECB}": "\u{DE}",
        "\u{1ECC}": "\u{E4}",
        "\u{1ECD}": "\u{E4}",
        "\u{1ECE}": "\u{E1}",
        "\u{1ECF}": "\u{E1}",
        "\u{1ED0}": "\u{E8}",
        "\u{1ED1}": "\u{E8}",
        "\u{1ED2}": "\u{E5}",
        "\u{1ED3}": "\u{E5}",
        "\u{1ED4}": "\u{E6}",
        "\u{1ED5}": "\u{E6}",
        "\u{1ED6}": "\u{E7}",
        "\u{1ED7}": "\u{E7}",
        "\u{1ED8}": "\u{E9}",
        "\u{1ED9}": "\u{E9}",
        "\u{1EDA}": "\u{ED}",
        "\u{1EDB}": "\u{ED}",
        "\u{1EDC}": "\u{EA}",
        "\u{1EDD}": "\u{EA}",
        "\u{1EDE}": "\u{EB}",
        "\u{1EDF}": "\u{EB}",
        "\u{1EE0}": "\u{EC}",
        "\u{1EE1}": "\u{EC}",
        "\u{1EE2}": "\u{EE}",
        "\u{1EE3}": "\u{EE}",
        "\u{1EE4}": "\u{F4}",
        "\u{1EE5}": "\u{F4}",
        "\u{1EE6}": "\u{F1}",
        "\u{1EE7}": "\u{F1}",
        "\u{1EE8}": "\u{F8}",
        "\u{1EE9}": "\u{F8}",
        "\u{1EEA}": "\u{F5}",
        "\u{1EEB}": "\u{F5}",
        "\u{1EEC}": "\u{F6}",
        "\u{1EED}": "\u{F6}",
        "\u{1EEE}": "\u{F7}",
        "\u{1EEF}": "\u{F7}",
        "\u{1EF0}": "\u{F9}",
        "\u{1EF1}": "\u{F9}",
        "\u{1EF2}": "\u{FA}",
        "\u{1EF3}": "\u{FA}",
        "\u{1EF4}": "\u{FE}",
        "\u{1EF5}": "\u{FE}",
        "\u{1EF6}": "\u{FB}",
        "\u{1EF7}": "\u{FB}",
        "\u{1EF8}": "\u{FC}",
        "\u{1EF9}": "\u{FC}",
    ]
    // unicodeToVNI: 134 ký tự
    static let unicodeToVNI: [Character: String] = [
        "\u{C0}": "\u{41}\u{D8}",
        "\u{C1}": "\u{41}\u{D9}",
        "\u{C2}": "\u{41}\u{C2}",
        "\u{C3}": "\u{41}\u{D5}",
        "\u{C8}": "\u{45}\u{D8}",
        "\u{C9}": "\u{45}\u{D9}",
        "\u{CA}": "\u{45}\u{C2}",
        "\u{CC}": "\u{CC}",
        "\u{CD}": "\u{CD}",
        "\u{D2}": "\u{4F}\u{D8}",
        "\u{D3}": "\u{4F}\u{D9}",
        "\u{D4}": "\u{4F}\u{C2}",
        "\u{D5}": "\u{4F}\u{D5}",
        "\u{D9}": "\u{55}\u{D8}",
        "\u{DA}": "\u{55}\u{D9}",
        "\u{DD}": "\u{59}\u{D9}",
        "\u{E0}": "\u{61}\u{F8}",
        "\u{E1}": "\u{61}\u{F9}",
        "\u{E2}": "\u{61}\u{E2}",
        "\u{E3}": "\u{61}\u{F5}",
        "\u{E8}": "\u{65}\u{F8}",
        "\u{E9}": "\u{65}\u{F9}",
        "\u{EA}": "\u{65}\u{E2}",
        "\u{EC}": "\u{EC}",
        "\u{ED}": "\u{ED}",
        "\u{F2}": "\u{6F}\u{F8}",
        "\u{F3}": "\u{6F}\u{F9}",
        "\u{F4}": "\u{6F}\u{E2}",
        "\u{F5}": "\u{6F}\u{F5}",
        "\u{F9}": "\u{75}\u{F8}",
        "\u{FA}": "\u{75}\u{F9}",
        "\u{FD}": "\u{79}\u{F9}",
        "\u{102}": "\u{41}\u{CA}",
        "\u{103}": "\u{61}\u{EA}",
        "\u{110}": "\u{D1}",
        "\u{111}": "\u{F1}",
        "\u{128}": "\u{D3}",
        "\u{129}": "\u{F3}",
        "\u{168}": "\u{55}\u{D5}",
        "\u{169}": "\u{75}\u{F5}",
        "\u{1A0}": "\u{D4}",
        "\u{1A1}": "\u{F4}",
        "\u{1AF}": "\u{D6}",
        "\u{1B0}": "\u{F6}",
        "\u{1EA0}": "\u{41}\u{CF}",
        "\u{1EA1}": "\u{61}\u{EF}",
        "\u{1EA2}": "\u{41}\u{DB}",
        "\u{1EA3}": "\u{61}\u{FB}",
        "\u{1EA4}": "\u{41}\u{C1}",
        "\u{1EA5}": "\u{61}\u{E1}",
        "\u{1EA6}": "\u{41}\u{C0}",
        "\u{1EA7}": "\u{61}\u{E0}",
        "\u{1EA8}": "\u{41}\u{C5}",
        "\u{1EA9}": "\u{61}\u{E5}",
        "\u{1EAA}": "\u{41}\u{C3}",
        "\u{1EAB}": "\u{61}\u{E3}",
        "\u{1EAC}": "\u{41}\u{C4}",
        "\u{1EAD}": "\u{61}\u{E4}",
        "\u{1EAE}": "\u{41}\u{C9}",
        "\u{1EAF}": "\u{61}\u{E9}",
        "\u{1EB0}": "\u{41}\u{C8}",
        "\u{1EB1}": "\u{61}\u{E8}",
        "\u{1EB2}": "\u{41}\u{DA}",
        "\u{1EB3}": "\u{61}\u{FA}",
        "\u{1EB4}": "\u{41}\u{DC}",
        "\u{1EB5}": "\u{61}\u{FC}",
        "\u{1EB6}": "\u{41}\u{CB}",
        "\u{1EB7}": "\u{61}\u{EB}",
        "\u{1EB8}": "\u{45}\u{CF}",
        "\u{1EB9}": "\u{65}\u{EF}",
        "\u{1EBA}": "\u{45}\u{DB}",
        "\u{1EBB}": "\u{65}\u{FB}",
        "\u{1EBC}": "\u{45}\u{D5}",
        "\u{1EBD}": "\u{65}\u{F5}",
        "\u{1EBE}": "\u{45}\u{C1}",
        "\u{1EBF}": "\u{65}\u{E1}",
        "\u{1EC0}": "\u{45}\u{C0}",
        "\u{1EC1}": "\u{65}\u{E0}",
        "\u{1EC2}": "\u{45}\u{C5}",
        "\u{1EC3}": "\u{65}\u{E5}",
        "\u{1EC4}": "\u{45}\u{C3}",
        "\u{1EC5}": "\u{65}\u{E3}",
        "\u{1EC6}": "\u{45}\u{C4}",
        "\u{1EC7}": "\u{65}\u{E4}",
        "\u{1EC8}": "\u{C6}",
        "\u{1EC9}": "\u{E6}",
        "\u{1ECA}": "\u{D2}",
        "\u{1ECB}": "\u{F2}",
        "\u{1ECC}": "\u{4F}\u{CF}",
        "\u{1ECD}": "\u{6F}\u{EF}",
        "\u{1ECE}": "\u{4F}\u{DB}",
        "\u{1ECF}": "\u{6F}\u{FB}",
        "\u{1ED0}": "\u{4F}\u{C1}",
        "\u{1ED1}": "\u{6F}\u{E1}",
        "\u{1ED2}": "\u{4F}\u{C0}",
        "\u{1ED3}": "\u{6F}\u{E0}",
        "\u{1ED4}": "\u{4F}\u{C5}",
        "\u{1ED5}": "\u{6F}\u{E5}",
        "\u{1ED6}": "\u{4F}\u{C3}",
        "\u{1ED7}": "\u{6F}\u{E3}",
        "\u{1ED8}": "\u{4F}\u{C4}",
        "\u{1ED9}": "\u{6F}\u{E4}",
        "\u{1EDA}": "\u{D4}\u{D9}",
        "\u{1EDB}": "\u{F4}\u{F9}",
        "\u{1EDC}": "\u{D4}\u{D8}",
        "\u{1EDD}": "\u{F4}\u{F8}",
        "\u{1EDE}": "\u{D4}\u{DB}",
        "\u{1EDF}": "\u{F4}\u{FB}",
        "\u{1EE0}": "\u{D4}\u{D5}",
        "\u{1EE1}": "\u{F4}\u{F5}",
        "\u{1EE2}": "\u{D4}\u{CF}",
        "\u{1EE3}": "\u{F4}\u{EF}",
        "\u{1EE4}": "\u{55}\u{CF}",
        "\u{1EE5}": "\u{75}\u{EF}",
        "\u{1EE6}": "\u{55}\u{DB}",
        "\u{1EE7}": "\u{75}\u{FB}",
        "\u{1EE8}": "\u{D6}\u{D9}",
        "\u{1EE9}": "\u{F6}\u{F9}",
        "\u{1EEA}": "\u{D6}\u{D8}",
        "\u{1EEB}": "\u{F6}\u{F8}",
        "\u{1EEC}": "\u{D6}\u{DB}",
        "\u{1EED}": "\u{F6}\u{FB}",
        "\u{1EEE}": "\u{D6}\u{D5}",
        "\u{1EEF}": "\u{F6}\u{F5}",
        "\u{1EF0}": "\u{D6}\u{CF}",
        "\u{1EF1}": "\u{F6}\u{EF}",
        "\u{1EF2}": "\u{59}\u{D8}",
        "\u{1EF3}": "\u{79}\u{F8}",
        "\u{1EF4}": "\u{CE}",
        "\u{1EF5}": "\u{EE}",
        "\u{1EF6}": "\u{59}\u{DB}",
        "\u{1EF7}": "\u{79}\u{FB}",
        "\u{1EF8}": "\u{59}\u{D5}",
        "\u{1EF9}": "\u{79}\u{F5}",
    ]

    /// TCVN3 -> Unicode (đảo của unicodeToTCVN). TCVN3 là 1 ký tự nên đảo trực tiếp.
    ///
    /// LƯU Ý: TCVN3 dùng CHUNG một byte cho nguyên âm-có-dấu HOA và thường
    /// (vd "Ế" và "ế" đều là byte 0x00D5). Đây là tính chất cố hữu của bảng mã —
    /// không thể khôi phục chính xác hoa/thường khi giải mã. Ta ưu tiên trả về
    /// dạng THƯỜNG (phổ biến hơn); chỉnh lại bằng công cụ "Hoa mỗi từ"/"Hoa đầu
    /// câu" sau nếu cần.
    static let tcvnToUnicode: [Character: Character] = {
        var m: [Character: Character] = [:]
        for (uni, legacy) in unicodeToTCVN where legacy.count == 1 {
            let key = legacy.first!
            if let existing = m[key] {
                if existing.isUppercase && uni.isLowercase { m[key] = uni }
            } else {
                m[key] = uni
            }
        }
        return m
    }()

    /// VNI-Windows -> Unicode. Khoá là chuỗi (1-2 ký tự) -> ánh xạ ngược.
    /// Khi giải mã ta thử khớp chuỗi 2 ký tự trước, rồi 1 ký tự.
    static let vniToUnicode: [String: Character] = {
        var m: [String: Character] = [:]
        for (uni, legacy) in unicodeToVNI { m[legacy] = uni }
        return m
    }()

    /// Độ dài tối đa của một token VNI (số ký tự) — để giải mã greedy.
    static let vniMaxTokenLength = 2
}
